### ISSUE TITLE
Indexerror for reverted transaction in txnHistory

### ISSUE THREAD

**Issue by Kasche153** [jeffchen006/OpenTracer#2]
# System
* Macbook Pro M1 Max
* macOS Ventura Version 13.0
# Transaction
0x1f7f9a55b03238667f17c3b1aa41bcff4e79ffb0820a5b309bbed0f8ddeb9ae4
# Parameters 
```python 
      contract = "0xe952bda8c06481506e4731c4f54ced2d4ab81659" 
      endBlock=14465357
      l1=[]
      l2=[]
      l3=[]
```

# Errormessage
```
Traceback (most recent call last):
  File "/Users/gustavkasche/OpenTracer/OpenTracer/main.py", line 743, in <module>
    main()
  File "/Users/gustavkasche/OpenTracer/OpenTracer/main.py", line 387, in main
    collectTraceAndInvariants(contract="0xe952bda8c06481506e4731c4f54ced2d4ab81659", endBlock=14465357, l1=[], l2=[], l3=[])
  File "/Users/gustavkasche/OpenTracer/OpenTracer/main.py", line 637, in collectTraceAndInvariants
    dataSourceMapList, accessList, splitedTraceTree = analyzeOneTx(contract, txHashes[ii], pathList[ii], l1, l2, l3)        
  File "/Users/gustavkasche/OpenTracer/OpenTracer/parserPackage/parser.py", line 1625, in analyzeOneTx
    metaTraceTree = p.parseLogs(contract, Tx, trace)
  File "/Users/gustavkasche/OpenTracer/OpenTracer/parserPackage/parser.py", line 988, in parseLogs
    metaTraceTree.updateInfo({"structLogsEnd": ii}, self.logging)
  File "/Users/gustavkasche/OpenTracer/OpenTracer/parserPackage/traceTree.py", line 245, in updateInfo
    self.internalCalls[-1].updateInfo(dict)
IndexError: list index out of range

```

**Comment by jeffchen006** [comment]
plan to finish next week.

**Comment by jeffchen006** [comment]
The feature of inferring invariants have been deprecated in OpenTracer, as users are more interested in its transaction explorer feature instead of its invariant generation feature. 

The invariant generation feature will been maintained in our FSE 2024 Artifact repo:

https://github.com/jeffchen006/Trace2Inv-Artifact-FSE24
