### ISSUE TITLE
what should i do to solve the problem about“File "C:\Users\ASUS\.conda\envs\opentracer\lib\json\decoder.py", line 355, in raw_decode”

### ISSUE THREAD

**Issue by HenryHuang0428** [jeffchen006/OpenTracer#5]
Traceback (most recent call last):
  File "d:\GoogleDownload\OpenTracer-main\main.py", line 746, in <module>
    main()
  File "d:\GoogleDownload\OpenTracer-main\main.py", line 386, in main
    feature1()
  File "d:\GoogleDownload\OpenTracer-main\main.py", line 435, in feature1
    txHashes = collectTransactionHistory(contract, endBlock)
  File "d:\GoogleDownload\OpenTracer-main\main.py", line 29, in collectTransactionHistory
    txHashes = crawler.Contract2TxHistory(contractAddress, endBlock)
  File "d:\GoogleDownload\OpenTracer-main\crawlPackage\crawl.py", line 50, in Contract2TxHistory
    HistoryBlockIndex = self.Contract2TxHistoryBlockIndex(contractAddress, endBlock, maxTxs)
  File "d:\GoogleDownload\OpenTracer-main\crawlPackage\crawl.py", line 26, in Contract2TxHistoryBlockIndex
    ContractTxHistoryBlockIndex = CrawlTrueBlocks().Contract2TxHistoryBlockIndex(contractAddress)
  File "d:\GoogleDownload\OpenTracer-main\crawlPackage\crawlTrueBlocks.py", line 29, in Contract2TxHistoryBlockIndex
    output_json = json.loads(output)
  File "C:\Users\ASUS\.conda\envs\opentracer\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\ASUS\.conda\envs\opentracer\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\ASUS\.conda\envs\opentracer\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by jeffchen006** [comment]
Thank you! Did you already install trueBlocks?

**Comment by HenryHuang0428** [comment]
solved!thank you!
